### 03 实现一个函数，把字符串s中的每个空格替换为%20

eg. 输入 s = "we are happy."

In [1]:
s = "we are happy."
s_new = ""
for i in s:
    if i == " ":
        s_new = s_new + "%20"
    else:
        s_new = s_new + i
print(s_new)

we%20are%20happy.


knowledge：list;
time complexity：O(N);
space complexity: O(N)

### 06 从尾到头打印链表
eg. 输入：head = [1,3,2]

In [2]:
def printArr(a:list):
    return [a.pop() for i in range(0,len(a))]

In [28]:
head = [2,3,1]
printArr(head)

[1, 3, 2]

knowledge：
列表list可以是栈，先入（push）后出（pop），以上解法用的是栈。

In [2]:
class ListNode:
    def __init__(self, x):
        self.value = x
        self.next = None

#建立链表
n1 = ListNode(2) 
n2 = ListNode(3)
n3 = ListNode(1)

n1.next = n2
n2.next = n3

In [29]:
class Solution():
    def reversePrint(self, head:ListNode) :
        return self.reversePrint(head.next) + [head.value] if head else [] # list中+就是添加元素。

In [30]:
ans = Solution()
ans.reversePrint(n1)

[1, 3, 2]

knowledge: 递归法。

class可以没有__init__()函数，先要实例化instance这个类，然后调用其方法。

In [6]:
class Solution():
    def reversePrint(self, head:ListNode) :
        stack = []
        while head:
            stack.append(head.value)
            head = head.next
        return stack[::-1]

In [4]:
ans = Solution()
ans.reversePrint(n1)

[1, 3, 2]

### 09. 用两个栈实现队列
两个栈实现一个队列。实现两个函数appendTail和deleteHead；
appendTail：在队列尾部插入整数；
deleteHead：在队列头部删除整数；若队列中没有元素，返回-1.

In [16]:
class Solution():

    def __init__(self):

        '''
        栈A  栈B
        | |  | |
        | |  |1|
        | |  |2|
        思路：
        1. 栈A存放队列的元素
        2. 栈B存放需要弹出的元素：
            如果栈B不为空，弹出栈B最上面的元素；
            如果栈B为空，将栈A的元素移到栈B中。
            栈A和栈B同时为空，返回-1
        '''
        self.A, self.B = [], []

    def appendTail(self, value: int) -> None:

        self.A.append(value)
        
    def deleteHead(self) -> int:

        if self.B:    
            return self.B.pop()

        if not self.A:
            return -1 #执行到return语句时，会退出函数
        
        if self.A:
            self.B = self.A[::-1]
            self.A = []    
            return self.B.pop()
        

In [18]:
#测试
Cque = Solution()
Cque.appendTail(3)
print(Cque.A)
print(Cque.deleteHead())
print(Cque.deleteHead())
print(Cque.deleteHead())


[3]
3
-1
-1


### 30 包含min函数的栈

ADT 抽象数据类型。
定义栈的数据结构，在该类型中实现一个能够的大栈的最小元素的min函数。min push pop的时间复杂度都是O(1)。
注意：min的时间复杂度为O(1)

In [23]:
import math
class MinStack:

    '''
    解体思路 -- 难点在于求min的时候时间复杂度是O(1)。考虑用辅助栈方法，辅助栈存储最小值。
    '''
    
    def __init__(self):
        self.stack1, self.min_stack = [], []

    def push(self,value: int):
        self.stack1.append(value)
        if self.min_stack == [] or value <= self.min_stack[-1]: # 必须要<=，等于的时候也要压入辅助栈中，否则pop之后再求min的时候就没有这个最小值了。
            self.min_stack.append(value)
    
    def pop(self):
        para = self.stack1.pop()
        if para == self.min_stack[-1]:
            self.min_stack.pop()
    
    def top(self):
        return self.stack1[-1]
    
    def min(self):
        if self.min_stack ==[]:
            return [math.inf]
        else:
            return self.min_stack[-1]

In [19]:
'''
示例
MinStack()
MinStack.push(0)
MinStack.push(0)
MinStack.push(-3)
minStack.min()  --> return -3
minStack.pop()
minStack.top()  --> return 0
minStack.min()  --> return 0
'''

'\n示例\nMinStack()\nMinStack.push(-2)\nMinStack.push(0)\nMinStack.push(-3)\nminStack.min()  --> return -3\nminStack.pop()\nminStack.top()  --> return 0\nminStack.min()  --> return -2\n\n'

### 24 反转链表并输出头节点。

In [9]:
class ListNode:
    def __init__(self, x):
        self.value = x
        self.next = None

# 建立链表
n1 = ListNode(1)
n2 = ListNode(2)
n3 = ListNode(5)

n1.next = n2
n2.next = n3  

In [ ]:
class Solution:
    def reverseListNode(self, n:ListNode):
        stack = []
        while n.value:
            stack.append(n.value)
            n = n.next
        stack_r = stack[::-1]
        ln = ListNode(stack_r[0])
        for i in range(0, len(stack_r)-2):
            ln.next = ListNode(stack_r[i+1])
            ln_tmp = ln
        return ln

In [44]:
import numpy as np
a = np.ones((3,3,5))

In [42]:
a.shape[:-1]

(3, 3)

In [46]:
b = a.reshape((-1, 3, 5))


In [59]:
#c = np.where()
print(np.ones(a.shape[:-1], dtype=np.bool_))
beams2correct = np.where(np.ones(a.shape[:-1], dtype=np.bool_))
print(beams2correct)
print(beams2correct[0])

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))
[0 0 0 1 1 1 2 2 2]


In [62]:
a[beams2correct]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
input = np.asarray(a)
input.dtype.kind

'i'